redis: &redis
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL", "redis://127.0.0.1:6379/0") %>
  channel_prefix: pixel_canvas

development:
  <<: *redis

test:
  adapter: test

production:
  <<: *redis
