source "https://rubygems.org"

ruby ">= 3.2"

gem "rails", "~> 8.0"

gem "connection_pool"
gem "mysql2", "~> 0.5"
gem "puma", ">= 6.0"
gem "rack-attack", "~> 6.7"
gem "redis", "~> 5.0"
gem "sidekiq", ">= 7.3", "< 9"
gem "tzinfo-data", platforms: %i[windows jruby]

group :development, :test do
  gem "rspec-rails", ">= 7.1"
  gem "rubocop", "~> 1.60", require: false
end
